# Hailo8 + NVIDIA AI加速服务部署配置
# 本地构建版本 - 解决网络连接问题

services:
  # Hailo8 + NVIDIA 双硬件AI推理服务
  hailo8-ai:
    build:
      context: ./hailo-runtime
      dockerfile: Dockerfile
      args:
        SUPPORT_NVIDIA: "true"
        SUPPORT_HAILO: "true"
    image: hailo8-nvidia-hailo:local
    container_name: hailo8-ai
    restart: unless-stopped
    shm_size: "256mb"
    privileged: true

    # NVIDIA GPU支持
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    ports:
      - "8000:8000"
      - "50051:50051"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./models:/app/models
      - ./logs:/app/logs
      - /dev/hailo0:/dev/hailo0
      - /dev/hailo1:/dev/hailo1
      - /dev/dri:/dev/dri
      - /lib/modules:/lib/modules:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000

    environment:
      - HAILO_API_HOST=0.0.0.0
      - HAILO_API_PORT=8000
      - HAILO_GRPC_PORT=50051
      - LOG_LEVEL=INFO
      - DEBUG=false
      - SUPPORT_HAILO=true
      - SUPPORT_NVIDIA=true
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=all
      - CUDA_MODULE_LOADING=LAZY
      - DEFAULT_ENGINE=auto
      - FALLBACK_ENGINE=hailo
      - REDIS_URL=redis://redis:6379
      - CACHE_ENABLED=true

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    depends_on:
      redis:
        condition: service_healthy

  # Redis缓存服务
  redis:
    image: redis:7-alpine
    container_name: hailo8-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  # 可选：监控服务
  prometheus:
    image: prom/prometheus:latest
    container_name: hailo8-prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'

    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: hailo8-grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=hailo8
      - GF_USERS_ALLOW_SIGN_UP=false

    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro

    depends_on:
      - prometheus

    profiles:
      - monitoring

# 数据卷定义
volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local