# Hailo8 + NVIDIA AI加速服务
# 为其他容器提供Hailo8和NVIDIA显卡加速服务

version: '3.8'

services:
  # Hailo8 + NVIDIA 双硬件加速推理服务
  ai-acceleration-service:
    build:
      context: ./hailo-runtime
      dockerfile: Dockerfile
      args:
        - SUPPORT_NVIDIA=true
        - SUPPORT_HAILO=true
    image: hailo8/nvidia-hailo:latest
    container_name: ai-acceleration-service
    restart: unless-stopped
    privileged: true  # 需要特权模式访问硬件

    ports:
      - "8000:8000"    # HTTP API
      - "50051:50051"  # gRPC服务
      - "8080:8080"    # 管理界面

    volumes:
      # Hailo8硬件访问
      - /dev/hailo0:/dev/hailo0
      - /dev/hailo1:/dev/hailo1
      # NVIDIA设备访问
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      # 内核模块
      - /lib/modules:/lib/modules:ro
      # 模型文件存储
      - ./models:/app/models:ro
      # 日志文件
      - ./logs:/app/logs
      # 临时文件
      - ./temp:/app/temp

    environment:
      - HAILO_API_HOST=0.0.0.0
      - HAILO_API_PORT=8000
      - HAILO_GRPC_PORT=50051
      - LOG_LEVEL=INFO
      - DEBUG=false

      # 硬件支持配置
      - SUPPORT_HAILO=true
      - SUPPORT_NVIDIA=true
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=all

      # 推理引擎配置
      - DEFAULT_ENGINE=auto  # auto/hailo/nvidia
      - FALLBACK_ENGINE=hailo

      # 缓存配置
      - REDIS_URL=redis://redis:6379
      - CACHE_ENABLED=true

    healthcheck:
      test: ["CMD", "/app/scripts/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    networks:
      - ai-acceleration-network

  # Redis缓存服务
  redis:
    image: redis:7-alpine
    container_name: ai-acceleration-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

    networks:
      - ai-acceleration-network

  # 监控服务
  prometheus:
    image: prom/prometheus:latest
    container_name: ai-acceleration-prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'

    networks:
      - ai-acceleration-network

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Grafana可视化
  grafana:
    image: grafana/grafana:latest
    container_name: ai-acceleration-grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=hailo8_nvidia
      - GF_USERS_ALLOW_SIGN_UP=false

    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro

    depends_on:
      - prometheus

    networks:
      - ai-acceleration-network

    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Portainer管理界面
  portainer:
    image: portainer/portainer-ce:latest
    container_name: ai-acceleration-portainer
    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

    networks:
      - ai-acceleration-network

# 数据卷定义
volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  portainer_data:
    driver: local

# 网络配置
networks:
  ai-acceleration-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
    labels:
      - "com.docker.compose.project=hailo8-nvidia-acceleration"