version: '3.8'

services:
  # Hailo8硬件加速服务 - 简化版本
  hailo8-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: hailo8-service:latest
    container_name: hailo8-service
    restart: unless-stopped
    
    # 网络配置
    ports:
      - "8080:8080"  # API服务端口
    
    # 环境变量
    environment:
      - SERVICE_NAME=Hailo8 Hardware Acceleration Service
      - SERVICE_VERSION=1.0.0
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=INFO
      - HAILO_MOCK_MODE=false
      - HAILO_DEVICE_COUNT=1
      - MAX_CONCURRENT_INFERENCES=4
      - MODEL_BASE_PATH=/app/models
    
    # 卷挂载
    volumes:
      # 模型存储目录
      - ./models:/app/models:ro
      # 日志目录
      - ./logs:/app/logs
    
    # 设备访问 - 访问Hailo8硬件
    devices:
      - /dev/hailo0:/dev/hailo0  # Hailo8设备节点
    
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s